# Day 8: Topic Discovery Proof-of-Concept (The Guaranteed Insight)

import nltk
from gensim import corpora
from gensim.models.ldamodel import LdaModel
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Ensure NLTK resources are downloaded (do this once)
try:
    nltk.data.find('corpora/stopwords')
except nltk.downloader.DownloadError:
    nltk.download('stopwords')
    nltk.download('punkt')

# 1. Sample summaries (Pretend these are the summaries generated by your LLM)
# Add some variety to ensure two topics emerge
generated_summaries = [
    "Patient was prescribed Metformin 500mg daily. We monitored blood sugar levels and adjusted dosage.",
    "A new radiation therapy protocol was applied to treat T-cell leukemia. Further study on the CD8 gene is needed.",
    "Imaging like CT scans is essential for diagnosis. Thoracoabdominal duplications are rare congenital malformations.",
    "Alzheimer's symptoms are being studied in Phase 2 trials. The drug Z-21 shows promise in reversing decline.",
    "Dosage adjustment is a key factor in managing diabetes. Metformin showed high efficacy."
]

# 2. Preprocessing (Tokenization and Stopword removal)
stop_words = set(stopwords.words('english'))
processed_docs = []

for text in generated_summaries:
    # Convert to lowercase, tokenize, and remove short words/stopwords
    tokens = [word.lower() for word in word_tokenize(text) 
              if word.isalpha() and word.lower() not in stop_words and len(word) > 2]
    processed_docs.append(tokens)

# 3. Create Dictionary and Corpus (The Data Structures for LDA)
# Dictionary maps every unique word to an ID
dictionary = corpora.Dictionary(processed_docs)
# Corpus converts the text into a Bag-of-Words format (ID and frequency)
corpus = [dictionary.doc2bow(doc) for doc in processed_docs]

# 4. Run the LDA Topic Model (The Knowledge Discovery Algorithm)
NUM_TOPICS = 2 # We want to find 2 main themes
lda_model = LdaModel(
    corpus,
    num_topics=NUM_TOPICS,
    id2word=dictionary,
    passes=10 # How many times the model looks at the data
)

# 5. Display the Insight
print("\n--- Knowledge Discovery Insights (Topic Modeling) ---")
print("Identifying Hidden Themes Across Summaries:\n")

for idx, topic in lda_model.print_topics(-1):
    print(f"Topic #{idx + 1}:")
    # Show the top 5 words driving that topic
    print(f"Keywords: {topic}\n")

print("------------------------------------------------------")
print("This proves the Knowledge Discovery component is working by autonomously identifying major themes.")