name: Deploy MedAI Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create zip package
        run: |
            zip -r app.zip app.py requirements.txt startup.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config appsettings set \
            --resource-group medai-rg \
            --name medai-backend \
            --settings \
              GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
              PG_HOST="medai-postgres-server.postgres.database.azure.com" \
              PG_USER="medai" \
              PG_PASSWORD="${{ secrets.PG_PASSWORD }}" \
              PG_DB="medical_insights" \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true

          az webapp deploy \
            --resource-group medai-rg \
            --name medai-backend \
            --src-path app.zip \
            --type zip

          az webapp config set \
            --resource-group medai-rg \
            --name medai-backend \
            --startup-file "gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 2 Ai_pipeline_backend:app"
